services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_CONNECTION_STRING=root:rahasia@tcp(db:3306)/test?charset=utf8mb4&parseTime=True&loc=Local

  db:
    image: bitnami/mysql
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=gromizk123
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-pgromizk123", "-e", "show schemas"]
      interval: 10s